-- supabase/migrations/20260226_create_operating_hours_table.sql

-- Add a column to flag 24/7 venues for simpler queries
ALTER TABLE "public"."places"
ADD COLUMN "is_24_7" BOOLEAN NOT NULL DEFAULT false;

-- Create a dedicated table for structured operating hours
CREATE TABLE "public"."operating_hours" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "place_id" UUID NOT NULL,
    "day_of_week" SMALLINT NOT NULL, -- ISO 8601: 1 = Monday, 7 = Sunday        
    "open_time" TIME WITHOUT TIME ZONE NOT NULL,
    "close_time" TIME WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT "operating_hours_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "operating_hours_place_id_fkey" FOREIGN KEY (place_id) REFERENCES places (id) ON DELETE CASCADE,
    CONSTRAINT "operating_hours_day_of_week_check" CHECK ((day_of_week >= 1) AND (day_of_week <= 7))
);

-- Add indexes for performance
CREATE INDEX "idx_operating_hours_place_id" ON "public"."operating_hours" USING "btree" ("place_id");
CREATE INDEX "idx_operating_hours_day_of_week" ON "public"."operating_hours" USING "btree" ("day_of_week");

-- Migrate "24/7" venues from the old text-based columns
-- Using DO block to safely handle migration of data
DO $$
BEGIN
    -- Drop check constraints if they exist, to allow the update
    IF EXISTS (SELECT 1 FROM information_schema.constraint_column_usage WHERE table_name = 'places' AND constraint_name = 'places_opening_time_hhmm_chk') THEN   
        ALTER TABLE "public"."places" DROP CONSTRAINT "places_opening_time_hhmm_chk";
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.constraint_column_usage WHERE table_name = 'places' AND constraint_name = 'places_closing_time_hhmm_chk') THEN   
        ALTER TABLE "public"."places" DROP CONSTRAINT "places_closing_time_hhmm_chk";
    END IF;

    -- Drop the trigger that depends on the columns being removed
    DROP TRIGGER IF EXISTS "update_status_before_change" ON "public"."places";  

    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='places' AND column_name='opening_time') THEN
        UPDATE "public"."places"
        SET "is_24_7" = true
        WHERE "opening_time" = '24/7';

        -- Drop old columns
        ALTER TABLE "public"."places" DROP COLUMN "opening_time";
        ALTER TABLE "public"."places" DROP COLUMN "closing_time";
    END IF;
END $$;

-- Grant access to the new table
GRANT ALL ON TABLE "public"."operating_hours" TO "postgres";
GRANT ALL ON TABLE "public"."operating_hours" TO "anon";
GRANT ALL ON TABLE "public"."operating_hours" TO "authenticated";
GRANT ALL ON TABLE "public"."operating_hours" TO "service_role";

-- Add RLS policies for the new table
ALTER TABLE "public"."operating_hours" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON "public"."operating_hours"
AS PERMISSIVE FOR SELECT
TO public
USING (true);
